services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: webhooks

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
    command: redis-server --save 60 1 --loglevel warning

  redisinsight:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - 5540:5540
    volumes:
      - ./redisinsight-data:/db
    depends_on:
      - redis
